name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install libraries
      run: sudo apt-get -y install libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: bin/farlands-tests

# build-windows:
#   runs-on: windows-latest

#   steps:
#   - uses: actions/checkout@v2

#   - name: Configure CMake
#     run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

#   - name: Build
#     run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#   - name: Test
#     working-directory: ${{github.workspace}}/build
#     run: bin/project-tests

# build-mac:
#   runs-on: macos-latest

#   steps:
#   - uses: actions/checkout@v2

#   - name: Configure CMake
#     run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

#   - name: Build
#     run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#   - name: Test
#     working-directory: ${{github.workspace}}/build
#     run: bin/project-tests


# doc:
#   runs-on: ubuntu-latest

#   steps:
#   - uses: actions/checkout@v2

#   - name: Configure CMake
#     run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

#   - name: Doc
#     run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target doc

      
